### ISSUE TITLE
Failed to fetch registry error.

### ISSUE THREAD

**Issue by ajay-bhargava** [magicuidesign/magicui#341]
**Describe the bug**

```bash
Error: Failed to fetch registry from https://magicui.design.
    at I (file:///Users/ajay/Projects/bynd.bio/v1/node_modules/magicui-cli/dist/index.js:60:3848)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Ie (file:///Users/ajay/Projects/bynd.bio/v1/node_modules/magicui-cli/dist/index.js:60:1420)
    at async Command.<anonymous> (file:///Users/ajay/Projects/bynd.bio/v1/node_modules/magicui-cli/dist/index.js:61:1962)
Failed to fetch components from Magic UI registry.
```

**To Reproduce**

Run
```bash
bunx magicui-cli add
```

Running: 
`Bun v1.1.29`
`"magicui-cli": "^0.1.6",`

**Expected behavior**
I expected to be presented with the selector screen for installing components. 

**Screenshots**
<img width="874" alt="Screenshot 2024-09-28 at 09 29 48" src="https://github.com/user-attachments/assets/6ee283a7-5b49-4526-ae95-0f37660d58ed">

**Desktop (please complete the following information):**
- MacOS Sonoma 14.6.1

**Comment by dillionverma** [comment]
Hi @ajay-bhargava thanks for pointing this out :) 

We decided to move forward with the shadcn cli for now since it's better maintained and works for other registries too

https://ui.shadcn.com/docs/cli
